disableSerialization;
closeDialog 8457;
createDialog"XM8ViewRules";
ExileClientXM8IsPowerOn = true;
_display = findDisplay 8458;
_ctrl = _display displayCtrl 4007;
_ctrl ctrlSetStructuredText parseText (format["<t shadow='1' shadowColor='#000000' size='2' color='#FF0000' align='center'>SERVER FEATURES</t>"]);
_ctrl = _display displayCtrl 40071;
_ctrl ctrlSetStructuredText parseText (format["<img align='right' size='3'  shadowColor='#000000' image='\exile_assets\texture\ui\xm8_app_territory_ca.paa'/>"]);
_ctrl = _display displayCtrl 4022;
_ctrl ctrlSetStructuredText parseText (format["<t align='left' color='#FF0000'>Server Rules</t>"]);
_ctrl = _display displayCtrl 4023;
_ctrl ctrlSetStructuredText parseText (format["<t align='left' color='#FF0000'>Our servers restart every 4 hours</t>"]);
_ctrl = _display displayCtrl 4024;
_ctrl ctrlSetStructuredText parseText (format["<t align='left' color='#FF0000'>No trader exploitation or Kamikaze</t>"]);
_ctrl = _display displayCtrl 4025;
_ctrl ctrlSetStructuredText parseText (format["<t align='left' color='#FF0000'>No spamming or Hacking/Glitching/Duping</t>"]);
_ctrl = _display displayCtrl 4026;
_ctrl ctrlSetStructuredText parseText (format["<t align='left' color='#FF0000'>No voice in Side/Global</t>"]);
_ctrl = _display displayCtrl 4027;
_ctrl ctrlSetStructuredText parseText (format["<t align='left' color='#FF0000'>No constructions blocking major military loot areas</t>"]);
_ctrl = _display displayCtrl 4028;
_ctrl ctrlSetStructuredText parseText (format["<t align='left' color='#FF0000'>Join the Forums: http://www.altf4gaming.com</t>"]);
_ctrl = _display displayCtrl 4029;
_ctrl ctrlSetStructuredText parseText (format["<t align='left' color='#FF0000'>Join Teamspeak: ts3.alt4gaming.com</t>"]);
_ctrl = _display displayCtrl 4030;
_ctrl ctrlSetStructuredText parseText (format["<t align='left' color='#FF0000'>For any issues including comps, glitches, or to report</t>"]);
_ctrl = _display displayCtrl 4031;
_ctrl ctrlSetStructuredText parseText (format["<t align='left' color='#FF0000'>hacking please use the forums!!!</t>"]);
_ctrl = _display displayCtrl 4032;
_ctrl ctrlSetStructuredText parseText (format["<t align='left'>/* <img size='0.5' shadowColor='#000000' image='\Exile_AiA_Building_Addon\images\UI\poptab_ca.paa'/> */Line 11</t>"]);
_ctrl = _display displayCtrl 4033;
_ctrl ctrlSetStructuredText parseText (format["<t align='left'>Line 12</t>"]);