/**
 * MAIN CONFIGURATION FILE
 * 
 * English and French comments
 * Commentaires anglais et français
 * 
 * (EN)
 * This file contains the configuration variables of the logistics system.
 * For the configuration of the creation factory, see the file "config_creation_factory.sqf".
 * IMPORTANT NOTE : when a logistics feature is given to an object/vehicle class name, all the classes which inherit
 *                  of the parent/generic class (according to the CfgVehicles) will also have this feature.
 *                  CfgVehicles tree view example : http://madbull.arma.free.fr/A3_stable_1.20.124746_CfgVehicles_tree.html
 * 
 * (FR)
 * Fichier contenant les variables de configuration du système de logistique.
 * Pour la configuration de l'usine de création, voir le fichier "config_creation_factory.sqf".
 * NOTE IMPORTANTE : lorsqu'une fonctionnalité logistique est accordée à un nom de classe d'objet/véhicule, les classes
 *                   héritant de cette classe mère/générique (selon le CfgVehicles) se verront également dotées de cette fonctionnalité.
 *                   Exemple d'arborescence du CfgVehicles : http://madbull.arma.free.fr/A3_stable_1.20.124746_CfgVehicles_tree.html
 */

/**
 * DISABLE LOGISTICS ON OBJECTS BY DEFAULT
 * 
 * (EN)
 * Define if objects and vehicles have logistics features by default,
 * or if it must be allowed explicitely on specific objects/vehicles.
 * 
 * If false : all objects are enabled according to the class names listed in this configuration file
 *            You can disable some objects with : object setVariable ["R3F_LOG_disabled", true];
 * If true :  all objects are disabled by default
 *            You can enable some objects with : object setVariable ["R3F_LOG_disabled", false];
 * 
 * 
 * (FR)
 * Défini si les objets et véhicules disposent des fonctionnalités logistiques par défaut,
 * ou si elles doivent être autorisés explicitement sur des objets/véhicules spécifiques.
 * 
 * Si false : tous les objets sont actifs en accord avec les noms de classes listés dans ce fichier
 *            Vous pouvez désactiver certains objets avec : objet setVariable ["R3F_LOG_disabled", true];
 * Si true :  tous les objets sont inactifs par défaut
 *            Vous pouvez activer quelques objets avec : objet setVariable ["R3F_LOG_disabled", false];
 */
R3F_LOG_CFG_disabled_by_default = false;

/**
 * LOCK THE LOGISTICS FEATURES TO SIDE, FACTION OR PLAYER
 * 
 * (EN)
 * Define the lock mode of the logistics features for an object.
 * An object can be locked to the a side, faction, a player (respawn) or a unit (life).
 * If the object is locked, the player can unlock it according to the
 * value of the config variable R3F_LOG_CFG_unlock_objects_timer.
 * 
 * If "none" : no lock features, everyone can used the logistics features.
 * If "side" : the object is locked to the last side which interacts with it.
 * If "faction" : the object is locked to the last faction which interacts with it.
 * If "player" : the object is locked to the last player which interacts with it. The lock is transmitted after respawn.
 * If "unit" : the object is locked to the last player which interacts with it. The lock is lost when the unit dies.
 * 
 * Note : for military objects (not civilian), the lock is initialized to the object's side.
 * 
 * See also the config variable R3F_LOG_CFG_unlock_objects_timer.
 * 
 * (FR)
 * Défini le mode de verrouillage des fonctionnalités logistics pour un objet donné.
 * Un objet peut être verrouillé pour une side, une faction, un joueur (respawn) ou une unité (vie).
 * Si l'objet est verrouillé, le joueur peut le déverrouiller en fonction de la
 * valeur de la variable de configiration R3F_LOG_CFG_unlock_objects_timer.
 * 
 * Si "none" : pas de verrouillage, tout le monde peut utiliser les fonctionnalités logistiques.
 * Si "side" : l'objet est verrouillé pour la dernière side ayant interagit avec lui.
 * Si "faction" : l'objet est verrouillé pour la dernière faction ayant interagit avec lui.
 * Si "player" : l'objet est verrouillé pour le dernier joueur ayant interagit avec lui. Le verrou est transmis après respawn.
 * Si "unit" : l'objet est verrouillé pour le dernier joueur ayant interagit avec lui. Le verrou est perdu quand l'unité meurt.
 * 
 * Note : pour les objets militaires (non civils), le verrou est initialisé à la side de l'objet.
 * 
 * Voir aussi la variable de configiration R3F_LOG_CFG_unlock_objects_timer.
 */
R3F_LOG_CFG_lock_objects_mode = "none";

/**
 * COUNTDOWN TO UNLOCK AN OBJECT
 * 
 * Define the countdown duration (in seconds) to unlock a locked object.
 * Set to -1 to deny the unlock of objects.
 * See also the config variable R3F_LOG_CFG_lock_objects_mode.
 * 
 * Défini la durée (en secondes) du compte-à-rebours pour déverrouiller un objet.
 * Mettre à -1 pour qu'on ne puisse pas déverrouiller les objets.
 * Voir aussi la variable de configiration R3F_LOG_CFG_lock_objects_mode.
 */
R3F_LOG_CFG_unlock_objects_timer = 30;

/**
 * ALLOW NO GRAVITY OVER GROUND
 * 
 * Define if movable objects with no gravity simulation can be set in height over the ground (no ground contact).
 * The no gravity objects corresponds to most of decoration and constructions items.
 * 
 * Défini si les objets déplaçable sans simulation de gravité peuvent être position en hauteur sans être contact avec le sol.
 * Les objets sans gravité correspondent à la plupart des objets de décors et de construction.
 */
R3F_LOG_CFG_no_gravity_objects_can_be_set_in_height_over_ground = true;

/**
 * LANGUAGE
 * 
 * Automatic language selection according to the game language.
 * New languages can be easily added (read below).
 * 
 * Sélection automatique de la langue en fonction de la langue du jeu.
 * De nouveaux langages peuvent facilement être ajoutés (voir ci-dessous).
 */
R3F_LOG_CFG_language = switch (language) do
{
	case "English":{"en"};
	case "French":{"fr"};
	
	// Feel free to create you own language file named "XX_strings_lang.sqf", where "XX" is the language code.
	// Make a copy of an existing language file (e.g. en_strings_lang.sqf) and translate it.
	// Then add a line with this syntax : case "YOUR_GAME_LANGUAGE":{"LANGUAGE_CODE"};
	// For example :
	
	//case "Czech":{"cz"}; // Not supported. Need your own "cz_strings_lang.sqf"
	//case "Polish":{"pl"}; // Not supported. Need your own "pl_strings_lang.sqf"
	//case "Portuguese":{"pt"}; // Not supported. Need your own "pt_strings_lang.sqf"
	//case "YOUR_GAME_LANGUAGE":{"LANGUAGE_CODE"};  // Need your own "LANGUAGE_CODE_strings_lang.sqf"
	
	default {"en"}; // If language is not supported, use English
};

/**
 * CONDITION TO ALLOW LOGISTICS
 * 
 * (EN)
 * This variable allow to set a dynamic SQF condition to allow/deny all logistics features only on specific clients.
 * The variable must be a STRING delimited by quotes and containing a valid SQF condition to evaluate during the game.
 * For example you can allow logistics only on few clients having a known game ID by setting the variable to :
 * "getPlayerUID player in [""76xxxxxxxxxxxxxxx"", ""76yyyyyyyyyyyyyyy"", ""76zzzzzzzzzzzzzzz""]"
 * Or based on the profile name : "profileName in [""john"", ""jack"", ""james""]"
 * Or only for the server admin : "serverCommandAvailable "#kick"""
 * The condition is evaluted in real time, so it can use condition depending on the mission progress : "alive officer && taskState task1 == ""Succeeded"""
 * Or to deny logistics in a circular area defined by a marker : "player distance getMarkerPos ""markerName"" > getMarkerSize ""markerName"" select 0"
 * Note that quotes of the strings inside the string condition must be doubled.
 * Note : if the condition depends of the aimed objects/vehicle, you can use the command cursorTarget
 * To allow the logistics to everyone, just set the condition to "true".
 * 
 * (FR)
 * Cette variable permet d'utiliser une condition SQF dynamique pour autoriser ou non les fonctions logistiques sur des clients spécifiques.
 * La variable doit être une CHAINE de caractères délimitée par des guillemets et doit contenir une condition SQF valide qui sera évaluée durant la mission.
 * Par exemple pour autoriser la logistique sur seulement quelques joueurs ayant un ID de jeu connu, la variable peut être défini comme suit :
 * "getPlayerUID player in [""76xxxxxxxxxxxxxxx"", ""76yyyyyyyyyyyyyyy"", ""76zzzzzzzzzzzzzzz""]"
 * Ou elle peut se baser sur le nom de profil : "profileName in [""maxime"", ""martin"", ""marc""]"
 * Ou pour n'autoriser que l'admin de serveur : "serverCommandAvailable "#kick"""
 * Les condition sont évaluées en temps réel, et peuvent donc dépendre du déroulement de la mission : "alive officier && taskState tache1 == ""Succeeded"""
 * Ou pour interdire la logistique dans la zone défini par un marqueur circulaire : "player distance getMarkerPos ""markerName"" > getMarkerSize ""markerName"" select 0"
 * Notez que les guillemets des chaînes de caractères dans la chaîne de condition doivent être doublés.
 * Note : si la condition dépend de l'objet/véhicule pointé, vous pouvez utiliser la commande cursorTarget
 * Pour autoriser la logistique chez tout le monde, il suffit de définir la condition à "true".
 */
R3F_LOG_CFG_string_condition_allow_logistics_on_this_client = "true";

/**
 * CONDITION TO ALLOW CREATION FACTORY
 * 
 * (EN)
 * This variable allow to set a dynamic SQF condition to allow/deny the access to the creation factory only on specific clients.
 * The variable must be a STRING delimited by quotes and containing a valid SQF condition to evaluate during the game.
 * For example you can allow the creation factory only on few clients having a known game ID by setting the variable to :
 * "getPlayerUID player in [""76xxxxxxxxxxxxxxx"", ""76yyyyyyyyyyyyyyy"", ""76zzzzzzzzzzzzzzz""]"
 * Or based on the profile name : "profileName in [""john"", ""jack"", ""james""]"
 * Or only for the server admin : "serverCommandAvailable "#kick"""
 * Note that quotes of the strings inside the string condition must be doubled.
 * Note : if the condition depends of the aimed objects/véhicule, you can use the command cursorTarget
 * Note also that the condition is evaluted in real time, so it can use condition depending on the mission progress :
 * "alive officer && taskState task1 == ""Succeeded"""
 * To allow the creation factory to everyone, just set the condition to "true".
 * 
 * (FR)
 * Cette variable permet d'utiliser une condition SQF dynamique pour rendre accessible ou non l'usine de création sur des clients spécifiques.
 * La variable doit être une CHAINE de caractères délimitée par des guillemets et doit contenir une condition SQF valide qui sera évaluée durant la mission.
 * Par exemple pour autoriser l'usine de création sur seulement quelques joueurs ayant un ID de jeu connu, la variable peut être défini comme suit :
 * "getPlayerUID player in [""76xxxxxxxxxxxxxxx"", ""76yyyyyyyyyyyyyyy"", ""76zzzzzzzzzzzzzzz""]"
 * Ou elle peut se baser sur le nom de profil : "profileName in [""maxime"", ""martin"", ""marc""]"
 * Ou pour n'autoriser que l'admin de serveur : "serverCommandAvailable "#kick"""
 * Notez que les guillemets des chaînes de caractères dans la chaîne de condition doivent être doublés.
 * Note : si la condition dépend de l'objet/véhicule pointé, vous pouvez utiliser la commande cursorTarget
 * Notez aussi que les condition sont évaluées en temps réel, et peuvent donc dépendre du déroulement de la mission :
 * "alive officier && taskState tache1 == ""Succeeded"""
 * Pour autoriser l'usine de création chez tout le monde, il suffit de définir la condition à "true".
 */
R3F_LOG_CFG_string_condition_allow_creation_factory_on_this_client = "false";

/*
 ********************************************************************************************
 * BELOW IS THE CLASS NAMES CONFIGURATION / CI-DESSOUS LA CONFIGURATION DES NOMS DE CLASSES *
 ********************************************************************************************
 * 
 * (EN)
 * There are two ways to manage new objects with the logistics system. The first one is to add these objects in the
 * following appropriate lists. The second one is to create a new external file in the /addons_config/ directory,
 * based on /addons_config/TEMPLATE.sqf, and to add a #include below to.
 * The first method is better to add/fix only some various class names.
 * The second method is better to take into account an additional addon.
 * 
 * These variables are based on the inheritance principle according to the CfgVehicles tree.
 * It means that a features accorded to a class name, is also accorded to all child classes.
 * Inheritance tree view : http://madbull.arma.free.fr/A3_1.32_CfgVehicles_tree.html
 * 
 * (FR)
 * Deux moyens existent pour gérer de nouveaux objets avec le système logistique. Le premier consiste à ajouter
 * ces objets dans les listes appropriées ci-dessous. Le deuxième est de créer un fichier externe dans le répertoire
 * /addons_config/ basé sur /addons_config/TEMPLATE.sqf, et d'ajouter un #include ci-dessous.
 * La première méthode est préférable lorsqu'il s'agit d'ajouter ou corriger quelques classes diverses.
 * La deuxième méthode est préférable s'il s'agit de prendre en compte le contenu d'un addon supplémentaire.
 * 
 * Ces variables sont basées sur le principe d'héritage utilisés dans l'arborescence du CfgVehicles.
 * Cela signifie qu'une fonctionnalité accordée à une classe, le sera aussi pour toutes ses classes filles.
 * Vue de l'arborescence d'héritage : http://madbull.arma.free.fr/A3_1.32_CfgVehicles_tree.html
 */

/****** LIST OF ADDONS CONFIG TO INCLUDE / LISTE DES CONFIG D'ADDONS A INCLURE ******/
#include "addons_config\A3_vanilla.sqf"
//#include "addons_config\All_in_Arma.sqf"
//#include "addons_config\R3F_addons.sqf"
//#include "addons_config\YOUR_ADDITIONAL_ADDON.sqf"

/****** TOW WITH VEHICLE / REMORQUER AVEC VEHICULE ******/

/**
 * List of class names of ground vehicles which can tow objects.
 * Liste des noms de classes des véhicules terrestres pouvant remorquer des objets.
 */
R3F_LOG_CFG_can_tow = R3F_LOG_CFG_can_tow +
[
	// e.g. : "MyTowingVehicleClassName1", "MyTowingVehicleClassName2"
	
	"Exile_Car_Offroad_Repair_Civillian",
	"Exile_Car_Offroad_Rusty1", 
	"Exile_Car_Offroad_Rusty2", 
	"Exile_Car_Offroad_Rusty3",
	"Exile_Car_Offroad_Repair_Red",
	"Exile_Car_Offroad_Red", 
	"Exile_Car_Offroad_Repair_Beige",
	"Exile_Car_Offroad_Repair_White",
	"Exile_Car_Offroad_Repair_Blue",
	"Exile_Car_Offroad_Repair_DarkRed",
	"Exile_Car_Offroad_Repair_BlueCustom",
	"Exile_Car_Offroad_Repair_Guerilla01",
	"Exile_Car_Offroad_Repair_Guerilla02",	
	"Exile_Car_Offroad_Repair_Guerilla03",
	"Exile_Car_Offroad_Repair_Guerilla04",
	"Exile_Car_Offroad_Repair_Guerilla05",
	"Exile_Car_Offroad_Repair_Guerilla06",
	"Exile_Car_Offroad_Repair_Guerilla07",
	"Exile_Car_Offroad_Repair_Guerilla08",
	"Exile_Car_Offroad_Repair_Guerilla09",
	"Exile_Car_Offroad_Repair_Guerilla10",
	"Exile_Car_Offroad_Repair_Guerilla11",
	"Exile_Car_Offroad_Repair_Guerilla12",
	"Exile_Car_Tempest",
	"Exile_Car_Zamak",
	"Exile_Car_HEMMT",
	"Exile_Car_Strider",
	"Exile_Car_Hunter",
	"Exile_Car_Ifrit",
	"Exile_Car_Offroad_Armed_Guerilla01", 
  	"Exile_Car_Offroad_Armed_Guerilla02", 
  	"Exile_Car_Offroad_Armed_Guerilla03", 
  	"Exile_Car_Offroad_Armed_Guerilla04", 
  	"Exile_Car_Offroad_Armed_Guerilla05", 
  	"Exile_Car_Offroad_Armed_Guerilla06", 
  	"Exile_Car_Offroad_Armed_Guerilla07", 
  	"Exile_Car_Offroad_Armed_Guerilla08", 
  	"Exile_Car_Offroad_Armed_Guerilla09", 
  	"Exile_Car_Offroad_Armed_Guerilla10", 
  	"Exile_Car_Offroad_Armed_Guerilla11", 
  	"Exile_Car_Offroad_Armed_Guerilla12",
  	"Exile_Car_SUV_Red", 
  	"Exile_Car_SUV_Black", 
  	"Exile_Car_SUV_Grey", 
  	"Exile_Car_SUV_Orange",
	"Exile_Car_Van_Black", 
  	"Exile_Car_Van_White", 
  	"Exile_Car_Van_Red", 
  	"Exile_Car_Van_Guerilla01", 
  	"Exile_Car_Van_Guerilla02", 
  	"Exile_Car_Van_Guerilla03", 
  	"Exile_Car_Van_Guerilla04", 
  	"Exile_Car_Van_Guerilla05", 
  	"Exile_Car_Van_Guerilla06", 
  	"Exile_Car_Van_Guerilla07", 
  	"Exile_Car_Van_Guerilla08",
  	"Exile_Car_Offroad_Rusty1", 
  	"Exile_Car_Offroad_Rusty2", 
  	"Exile_Car_Offroad_Rusty3", 
  	"Exile_Car_Offroad_Red", 
	"Exile_Car_Hatchback_Sport_White", 
	"Exile_Car_Hatchback_Sport_Beige", 
	"Exile_Car_Hatchback_Sport_Green",
	"Exile_Bike_QuadBike_Black", 
	"Exile_Bike_QuadBike_Blue", 
	"Exile_Bike_QuadBike_Red", 
	"Exile_Bike_QuadBike_White", 
	"Exile_Bike_QuadBike_Nato", 
	"Exile_Bike_QuadBike_Csat",
	"Exile_Bike_QuadBike_Fia", 
	"Exile_Bike_QuadBike_Guerilla01", 
	"Exile_Bike_QuadBike_Guerilla02", 
	"Exile_Car_Offroad_Repair_Civillian",
	"Exile_Car_Offroad_Repair_Red",
  	"Exile_Car_Offroad_Beige", 
  	"Exile_Car_Offroad_White", 
  	"Exile_Car_Offroad_Blue", 
  	"Exile_Car_Offroad_DarkRed", 
  	"Exile_Car_Offroad_BlueCustom", 
  	"Exile_Car_Offroad_Guerilla01", 
  	"Exile_Car_Offroad_Guerilla02", 
  	"Exile_Car_Offroad_Guerilla03", 
  	"Exile_Car_Offroad_Guerilla04", 
  	"Exile_Car_Offroad_Guerilla05", 
  	"Exile_Car_Offroad_Guerilla06", 
  	"Exile_Car_Offroad_Guerilla07", 
  	"Exile_Car_Offroad_Guerilla08", 
  	"Exile_Car_Offroad_Guerilla09", 
  	"Exile_Car_Offroad_Guerilla10", 
  	"Exile_Car_Offroad_Guerilla11", 
  	"Exile_Car_Offroad_Guerilla12",
	"Exile_Car_Van_Fuel_Black",
	"Exile_Car_Van_Fuel_Red",
	"Exile_Car_Van_Fuel_White",
	"Exile_Car_Van_Fuel_Guerilla01", 
	"Exile_Car_Van_Fuel_Guerilla02", 
	"Exile_Car_Van_Fuel_Guerilla03",
	"Exile_Car_Van_Box_Black",
	"Exile_Car_Van_Box_White",
	"Exile_Car_Van_Box_Red",
	"Exile_Car_Van_Box_Guerilla01", 
	"Exile_Car_Van_Box_Guerilla02", 
	"Exile_Car_Van_Box_Guerilla03", 
	"Exile_Car_Van_Box_Guerilla04", 
	"Exile_Car_Van_Box_Guerilla05", 
	"Exile_Car_Van_Box_Guerilla06", 
	"Exile_Car_Van_Box_Guerilla07", 
	"Exile_Car_Van_Box_Guerilla08",
	"Exile_Car_Lada_Green",
	"Exile_Car_Lada_Taxi",
	"Exile_Car_Lada_Red",
	"Exile_Car_Lada_White",
	"Exile_Car_Lada_Hipster",
	"Exile_Car_Volha_White",
	"Exile_Car_Volha_Blue",
	"Exile_Car_Volha_Black",
	"Exile_Car_SUVXL_Black",
	"Exile_Car_Ikarus_Blue",
	"Exile_Car_Ikarus_Red",
	"Exile_Car_Ikarus_Party",
	"Exile_Car_Ural_Open_Worker",
	"Exile_Car_Ural_Open_Blue",
	"Exile_Car_Ural_Open_Yellow",
	"Exile_Car_Ural_Open_Military",
	"Exile_Car_Ural_Covered_Worker",
	"Exile_Car_Ural_Covered_Blue",
	"Exile_Car_Ural_Covered_Yellow",
	"Exile_Car_Ural_Covered_Military",
	"CUP_C_Datsun",
	"CUP_C_Datsun_4seat",
	"CUP_C_Datsun_Plain",
	"CUP_C_Datsun_Covered",
	"CUP_C_Datsun_Tubeframe",
	"CUP_C_Ural_Civ_01",
	"CUP_C_Ural_Civ_02",
	"CUP_C_Ural_Civ_03",
	"CUP_C_Ural_Open_Civ_01",
	"CUP_C_Ural_Open_Civ_02",
	"CUP_C_Ural_Open_Civ_03",
	"CUP_O_Ural_TKA",
	"CUP_O_Ural_RU",
	"CUP_I_Ural_UN",
	"CUP_B_Ural_CDF",
	"CUP_O_Ural_CHDKZ",
	"CUP_O_Ural_SLA",
	"CUP_O_Ural_Open_TKA",
	"CUP_B_Ural_Open_CDF",
	"CUP_O_Ural_Open_RU",
	"CUP_O_Ural_Open_CHDKZ",
	"CUP_O_Ural_Open_SLA",
	"CUP_O_Ural_Empty_SLA",
	"CUP_B_Ural_Empty_CDF",
	"CUP_I_Ural_Empty_UN",
	"CUP_O_Ural_Empty_RU",
	"CUP_O_Ural_Empty_CHDKZ",
	"CUP_O_Ural_Empty_TKA",
	"CUP_O_Ural_Repair_SLA",
	"CUP_O_Ural_Repair_TKA",
	"CUP_O_Ural_Repair_CHDKZ",
	"CUP_O_Ural_Repair_RU",
	"CUP_I_Ural_Repair_UN",
	"CUP_B_Ural_Repair_CDF",
	"CUP_B_Ural_Refuel_CDF",
	"CUP_O_Ural_Refuel_RU",
	"CUP_O_Ural_Refuel_CHDKZ",
	"CUP_O_Ural_Refuel_TKA",
	"CUP_O_Ural_Refuel_SLA",
	"CUP_C_LR_Transport_CTK",
	"CUP_O_LR_Transport_TKA",
	"CUP_O_LR_Transport_TKM",
	"CUP_B_LR_Transport_CZ_W",
	"CUP_B_LR_Transport_CZ_D",
	"CUP_B_LR_Transport_GB_W",
	"CUP_B_LR_Transport_GB_D",
	"CUP_B_LR_Ambulance_CZ_W",
	"CUP_B_LR_Ambulance_CZ_D",
	"CUP_B_LR_Ambulance_GB_W",
	"CUP_B_LR_Ambulance_GB_D",
	"CUP_O_LR_Ambulance_TKA",
	"CUP_C_UAZ_Unarmed_TK_CIV",
	"CUP_O_UAZ_Unarmed_RU",
	"CUP_I_UAZ_Unarmed_UN",
	"CUP_O_UAZ_Unarmed_TKA",
	"CUP_O_UAZ_Unarmed_CHDKZ",
	"CUP_B_UAZ_Unarmed_ACR",
	"CUP_B_UAZ_Unarmed_CDF",
	"CUP_C_UAZ_Open_TK_CIV",
	"CUP_O_UAZ_Open_CHDKZ",
	"CUP_O_UAZ_Open_RU",
	"CUP_O_UAZ_Open_TKA",
	"CUP_I_UAZ_Open_UN",
	"CUP_B_UAZ_Open_ACR",
	"CUP_B_UAZ_Open_CDF",
	"CUP_B_HMMWV_Unarmed_USA",
	"CUP_B_HMMWV_Unarmed_USMC",
	"CUP_B_HMMWV_Ambulance_USMC",
	"CUP_B_HMMWV_Ambulance_USA",
	"CUP_B_HMMWV_Ambulance_ACR",
	"CUP_B_HMMWV_Transport_USA",
	"CUP_C_Golf4_whiteblood_Civ",
	"CUP_C_Golf4_camo_Civ",
	"CUP_C_Golf4_camodigital_Civ",
	"CUP_C_Golf4_camodark_Civ",
	"CUP_C_Golf4_reptile_Civ",
	"CUP_C_Golf4_kitty_Civ",
	"CUP_O_LR_MG_TKM",
	"CUP_O_LR_MG_TKA",
	"CUP_I_Datsun_PK",
	"CUP_I_Datsun_PK_Random",
	"CUP_I_Datsun_PK_TK",
	"CUP_I_Datsun_PK_TK_Random",
	"CUP_O_Datsun_PK",
	"CUP_O_Datsun_PK_Random",
	"CUP_O_UAZ_MG_CHDKZ",
	"CUP_O_UAZ_MG_RU",
	"CUP_O_UAZ_MG_TKA",
	"CUP_I_UAZ_MG_UN",
	"CUP_B_UAZ_MG_ACR",
	"CUP_B_UAZ_MG_CDF",
	"CUP_B_UAZ_AGS30_CDF",
	"CUP_O_UAZ_AGS30_CHDKZ",
	"CUP_O_UAZ_AGS30_RU",
	"CUP_O_UAZ_AGS30_TKA",
	"CUP_I_UAZ_AGS30_UN",
	"CUP_B_BRDM2_HQ_CDF",
	"CUP_O_BRDM2_HQ_SLA",
	"CUP_I_BRDM2_HQ_UN",
	"CUP_I_BRDM2_HQ_NAPA",
	"CUP_I_BRDM2_HQ_TK_Gue",
	"CUP_O_BRDM2_HQ_TKA",
	"CUP_O_BRDM2_HQ_CHDKZ",
	"CUP_O_BRDM2_CHDKZ",
	"CUP_O_BRDM2_SLA",
	"CUP_O_BRDM2_TKA",
	"CUP_I_BRDM2_NAPA",
	"CUP_I_BRDM2_TK_Gue",
	"CUP_I_BRDM2_UN",
	"CUP_B_BRDM2_CDF",
	"CUP_O_BTR60_TK",
	"CUP_O_BTR90_HQ_RU",
	"CUP_BAF_Jackal2_L2A1_W",
	"CUP_BAF_Jackal2_L2A1_D",
	"CUP_BAF_Jackal2_GMG_D",
	"CUP_BAF_Jackal2_GMG_W",
	"CUP_B_LR_Special_CZ_W",
	"CUP_B_LR_Special_Des_CZ_D",
	"CUP_B_LR_MG_CZ_W",
	"CUP_B_LR_MG_GB_W",
	"CUP_B_HMMWV_M1114_USMC",
	"CUP_B_HMMWV_M2_USMC",
	"CUP_B_HMMWV_Crows_M2_USA",
	"CUP_B_HMMWV_M2_GPK_USA",
	"CUP_B_HMMWV_M2_USA",
	"CUP_B_HMMWV_DSHKM_GPK_ACR",
	"CUP_B_HMMWV_AGS_GPK_ACR",
	"CUP_B_HMMWV_MK19_USMC",
	"CUP_B_HMMWV_MK19_USA",
	"CUP_B_HMMWV_Crows_MK19_USA",
	"CUP_B_HMMWV_SOV_USA",
	"I_MRAP_03_hmg_F",
	"B_MRAP_01_hmg_F"
];

/**
 * List of class names of objects which can be towed.
 * Liste des noms de classes des objets remorquables.
 */
R3F_LOG_CFG_can_be_towed = R3F_LOG_CFG_can_be_towed +
[
	// e.g. : "MyTowableObjectClassName1", "MyTowableObjectClassName2"
	
  
	"Exile_Car_Offroad_Repair_Civillian",
	"Exile_Car_Offroad_Rusty1", 
	"Exile_Car_Offroad_Rusty2", 
	"Exile_Car_Offroad_Rusty3",
	"Exile_Car_Offroad_Repair_Red",
	"Exile_Car_Offroad_Red", 
	"Exile_Car_Offroad_Repair_Beige",
	"Exile_Car_Offroad_Repair_White",
	"Exile_Car_Offroad_Repair_Blue",
	"Exile_Car_Offroad_Repair_DarkRed",
	"Exile_Car_Offroad_Repair_BlueCustom",
	"Exile_Car_Offroad_Repair_Guerilla01",
	"Exile_Car_Offroad_Repair_Guerilla02",	
	"Exile_Car_Offroad_Repair_Guerilla03",
	"Exile_Car_Offroad_Repair_Guerilla04",
	"Exile_Car_Offroad_Repair_Guerilla05",
	"Exile_Car_Offroad_Repair_Guerilla06",
	"Exile_Car_Offroad_Repair_Guerilla07",
	"Exile_Car_Offroad_Repair_Guerilla08",
	"Exile_Car_Offroad_Repair_Guerilla09",
	"Exile_Car_Offroad_Repair_Guerilla10",
	"Exile_Car_Offroad_Repair_Guerilla11",
	"Exile_Car_Offroad_Repair_Guerilla12",
	"Exile_Car_Tempest",
	"Exile_Car_Zamak",
	"Exile_Car_HEMMT",
	"Exile_Car_Strider",
	"Exile_Car_Hunter",
	"Exile_Car_Ifrit",
	"Exile_Car_Offroad_Armed_Guerilla01", 
  	"Exile_Car_Offroad_Armed_Guerilla02", 
  	"Exile_Car_Offroad_Armed_Guerilla03", 
  	"Exile_Car_Offroad_Armed_Guerilla04", 
  	"Exile_Car_Offroad_Armed_Guerilla05", 
  	"Exile_Car_Offroad_Armed_Guerilla06", 
  	"Exile_Car_Offroad_Armed_Guerilla07", 
  	"Exile_Car_Offroad_Armed_Guerilla08", 
  	"Exile_Car_Offroad_Armed_Guerilla09", 
  	"Exile_Car_Offroad_Armed_Guerilla10", 
  	"Exile_Car_Offroad_Armed_Guerilla11", 
  	"Exile_Car_Offroad_Armed_Guerilla12",
  	"Exile_Car_SUV_Red", 
  	"Exile_Car_SUV_Black", 
  	"Exile_Car_SUV_Grey", 
  	"Exile_Car_SUV_Orange",
	"Exile_Car_Van_Black", 
  	"Exile_Car_Van_White", 
  	"Exile_Car_Van_Red", 
  	"Exile_Car_Van_Guerilla01", 
  	"Exile_Car_Van_Guerilla02", 
  	"Exile_Car_Van_Guerilla03", 
  	"Exile_Car_Van_Guerilla04", 
  	"Exile_Car_Van_Guerilla05", 
  	"Exile_Car_Van_Guerilla06", 
  	"Exile_Car_Van_Guerilla07", 
  	"Exile_Car_Van_Guerilla08",
  	"Exile_Car_Offroad_Rusty1", 
  	"Exile_Car_Offroad_Rusty2", 
  	"Exile_Car_Offroad_Rusty3", 
  	"Exile_Car_Offroad_Red", 
	"Exile_Car_Hatchback_Sport_White", 
	"Exile_Car_Hatchback_Sport_Beige", 
	"Exile_Car_Hatchback_Sport_Green",
	"Exile_Bike_QuadBike_Black", 
	"Exile_Bike_QuadBike_Blue", 
	"Exile_Bike_QuadBike_Red", 
	"Exile_Bike_QuadBike_White", 
	"Exile_Bike_QuadBike_Nato", 
	"Exile_Bike_QuadBike_Csat",
	"Exile_Bike_QuadBike_Fia", 
	"Exile_Bike_QuadBike_Guerilla01", 
	"Exile_Bike_QuadBike_Guerilla02", 
	"Exile_Car_Offroad_Repair_Civillian",
	"Exile_Car_Offroad_Repair_Red",
  	"Exile_Car_Offroad_Beige", 
  	"Exile_Car_Offroad_White", 
  	"Exile_Car_Offroad_Blue", 
  	"Exile_Car_Offroad_DarkRed", 
  	"Exile_Car_Offroad_BlueCustom", 
  	"Exile_Car_Offroad_Guerilla01", 
  	"Exile_Car_Offroad_Guerilla02", 
  	"Exile_Car_Offroad_Guerilla03", 
  	"Exile_Car_Offroad_Guerilla04", 
  	"Exile_Car_Offroad_Guerilla05", 
  	"Exile_Car_Offroad_Guerilla06", 
  	"Exile_Car_Offroad_Guerilla07", 
  	"Exile_Car_Offroad_Guerilla08", 
  	"Exile_Car_Offroad_Guerilla09", 
  	"Exile_Car_Offroad_Guerilla10", 
  	"Exile_Car_Offroad_Guerilla11", 
  	"Exile_Car_Offroad_Guerilla12",
	"Exile_Car_Van_Fuel_Black",
	"Exile_Car_Van_Fuel_Red",
	"Exile_Car_Van_Fuel_White",
	"Exile_Car_Van_Fuel_Guerilla01", 
	"Exile_Car_Van_Fuel_Guerilla02", 
	"Exile_Car_Van_Fuel_Guerilla03",
	"Exile_Car_Van_Box_Black",
	"Exile_Car_Van_Box_White",
	"Exile_Car_Van_Box_Red",
	"Exile_Car_Van_Box_Guerilla01", 
	"Exile_Car_Van_Box_Guerilla02", 
	"Exile_Car_Van_Box_Guerilla03", 
	"Exile_Car_Van_Box_Guerilla04", 
	"Exile_Car_Van_Box_Guerilla05", 
	"Exile_Car_Van_Box_Guerilla06", 
	"Exile_Car_Van_Box_Guerilla07", 
	"Exile_Car_Van_Box_Guerilla08",
	"Exile_Car_Lada_Green",
	"Exile_Car_Lada_Taxi",
	"Exile_Car_Lada_Red",
	"Exile_Car_Lada_White",
	"Exile_Car_Lada_Hipster",
	"Exile_Car_Volha_White",
	"Exile_Car_Volha_Blue",
	"Exile_Car_Volha_Black",
	"Exile_Car_SUVXL_Black",
	"Exile_Car_Ikarus_Blue",
	"Exile_Car_Ikarus_Red",
	"Exile_Car_Ikarus_Party",
	"Exile_Car_Ural_Open_Worker",
	"Exile_Car_Ural_Open_Blue",
	"Exile_Car_Ural_Open_Yellow",
	"Exile_Car_Ural_Open_Military",
	"Exile_Car_Ural_Covered_Worker",
	"Exile_Car_Ural_Covered_Blue",
	"Exile_Car_Ural_Covered_Yellow",
	"Exile_Car_Ural_Covered_Military",
	"CUP_C_Datsun",
	"CUP_C_Datsun_4seat",
	"CUP_C_Datsun_Plain",
	"CUP_C_Datsun_Covered",
	"CUP_C_Datsun_Tubeframe",
	"CUP_C_Ural_Civ_01",
	"CUP_C_Ural_Civ_02",
	"CUP_C_Ural_Civ_03",
	"CUP_C_Ural_Open_Civ_01",
	"CUP_C_Ural_Open_Civ_02",
	"CUP_C_Ural_Open_Civ_03",
	"CUP_O_Ural_TKA",
	"CUP_O_Ural_RU",
	"CUP_I_Ural_UN",
	"CUP_B_Ural_CDF",
	"CUP_O_Ural_CHDKZ",
	"CUP_O_Ural_SLA",
	"CUP_O_Ural_Open_TKA",
	"CUP_B_Ural_Open_CDF",
	"CUP_O_Ural_Open_RU",
	"CUP_O_Ural_Open_CHDKZ",
	"CUP_O_Ural_Open_SLA",
	"CUP_O_Ural_Empty_SLA",
	"CUP_B_Ural_Empty_CDF",
	"CUP_I_Ural_Empty_UN",
	"CUP_O_Ural_Empty_RU",
	"CUP_O_Ural_Empty_CHDKZ",
	"CUP_O_Ural_Empty_TKA",
	"CUP_O_Ural_Repair_SLA",
	"CUP_O_Ural_Repair_TKA",
	"CUP_O_Ural_Repair_CHDKZ",
	"CUP_O_Ural_Repair_RU",
	"CUP_I_Ural_Repair_UN",
	"CUP_B_Ural_Repair_CDF",
	"CUP_B_Ural_Refuel_CDF",
	"CUP_O_Ural_Refuel_RU",
	"CUP_O_Ural_Refuel_CHDKZ",
	"CUP_O_Ural_Refuel_TKA",
	"CUP_O_Ural_Refuel_SLA",
	"CUP_C_LR_Transport_CTK",
	"CUP_O_LR_Transport_TKA",
	"CUP_O_LR_Transport_TKM",
	"CUP_B_LR_Transport_CZ_W",
	"CUP_B_LR_Transport_CZ_D",
	"CUP_B_LR_Transport_GB_W",
	"CUP_B_LR_Transport_GB_D",
	"CUP_B_LR_Ambulance_CZ_W",
	"CUP_B_LR_Ambulance_CZ_D",
	"CUP_B_LR_Ambulance_GB_W",
	"CUP_B_LR_Ambulance_GB_D",
	"CUP_O_LR_Ambulance_TKA",
	"CUP_C_UAZ_Unarmed_TK_CIV",
	"CUP_O_UAZ_Unarmed_RU",
	"CUP_I_UAZ_Unarmed_UN",
	"CUP_O_UAZ_Unarmed_TKA",
	"CUP_O_UAZ_Unarmed_CHDKZ",
	"CUP_B_UAZ_Unarmed_ACR",
	"CUP_B_UAZ_Unarmed_CDF",
	"CUP_C_UAZ_Open_TK_CIV",
	"CUP_O_UAZ_Open_CHDKZ",
	"CUP_O_UAZ_Open_RU",
	"CUP_O_UAZ_Open_TKA",
	"CUP_I_UAZ_Open_UN",
	"CUP_B_UAZ_Open_ACR",
	"CUP_B_UAZ_Open_CDF",
	"CUP_B_HMMWV_Unarmed_USA",
	"CUP_B_HMMWV_Unarmed_USMC",
	"CUP_B_HMMWV_Ambulance_USMC",
	"CUP_B_HMMWV_Ambulance_USA",
	"CUP_B_HMMWV_Ambulance_ACR",
	"CUP_B_HMMWV_Transport_USA",
	"CUP_C_Golf4_whiteblood_Civ",
	"CUP_C_Golf4_camo_Civ",
	"CUP_C_Golf4_camodigital_Civ",
	"CUP_C_Golf4_camodark_Civ",
	"CUP_C_Golf4_reptile_Civ",
	"CUP_C_Golf4_kitty_Civ",
	"CUP_O_LR_MG_TKM",
	"CUP_O_LR_MG_TKA",
	"CUP_I_Datsun_PK",
	"CUP_I_Datsun_PK_Random",
	"CUP_I_Datsun_PK_TK",
	"CUP_I_Datsun_PK_TK_Random",
	"CUP_O_Datsun_PK",
	"CUP_O_Datsun_PK_Random",
	"CUP_O_UAZ_MG_CHDKZ",
	"CUP_O_UAZ_MG_RU",
	"CUP_O_UAZ_MG_TKA",
	"CUP_I_UAZ_MG_UN",
	"CUP_B_UAZ_MG_ACR",
	"CUP_B_UAZ_MG_CDF",
	"CUP_B_UAZ_AGS30_CDF",
	"CUP_O_UAZ_AGS30_CHDKZ",
	"CUP_O_UAZ_AGS30_RU",
	"CUP_O_UAZ_AGS30_TKA",
	"CUP_I_UAZ_AGS30_UN",
	"CUP_B_BRDM2_HQ_CDF",
	"CUP_O_BRDM2_HQ_SLA",
	"CUP_I_BRDM2_HQ_UN",
	"CUP_I_BRDM2_HQ_NAPA",
	"CUP_I_BRDM2_HQ_TK_Gue",
	"CUP_O_BRDM2_HQ_TKA",
	"CUP_O_BRDM2_HQ_CHDKZ",
	"CUP_O_BRDM2_CHDKZ",
	"CUP_O_BRDM2_SLA",
	"CUP_O_BRDM2_TKA",
	"CUP_I_BRDM2_NAPA",
	"CUP_I_BRDM2_TK_Gue",
	"CUP_I_BRDM2_UN",
	"CUP_B_BRDM2_CDF",
	"CUP_O_BTR60_TK",
	"CUP_O_BTR90_HQ_RU",
	"CUP_BAF_Jackal2_L2A1_W",
	"CUP_BAF_Jackal2_L2A1_D",
	"CUP_BAF_Jackal2_GMG_D",
	"CUP_BAF_Jackal2_GMG_W",
	"CUP_B_LR_Special_CZ_W",
	"CUP_B_LR_Special_Des_CZ_D",
	"CUP_B_LR_MG_CZ_W",
	"CUP_B_LR_MG_GB_W",
	"CUP_B_HMMWV_M1114_USMC",
	"CUP_B_HMMWV_M2_USMC",
	"CUP_B_HMMWV_Crows_M2_USA",
	"CUP_B_HMMWV_M2_GPK_USA",
	"CUP_B_HMMWV_M2_USA",
	"CUP_B_HMMWV_DSHKM_GPK_ACR",
	"CUP_B_HMMWV_AGS_GPK_ACR",
	"CUP_B_HMMWV_MK19_USMC",
	"CUP_B_HMMWV_MK19_USA",
	"CUP_B_HMMWV_Crows_MK19_USA",
	"CUP_B_HMMWV_SOV_USA",
	"I_MRAP_03_hmg_F",
	"B_MRAP_01_hmg_F"
];


/****** LIFT WITH VEHICLE / HELIPORTER AVEC VEHICULE ******/

/**
 * List of class names of helicopters which can lift objects.
 * Liste des noms de classes des hélicoptères pouvant héliporter des objets.
 */
R3F_LOG_CFG_can_lift = R3F_LOG_CFG_can_lift +
[
	// e.g. : "MyLifterVehicleClassName1", "MyLifterVehicleClassName2"
	// Here comes the Classname for the Chopper can Lift
/* 	"Exile_Chopper_Hummingbird_Green",
	"Exile_Chopper_Hummingbird_Civillian_Wasp",
	"Exile_Chopper_Taru_Black",
	"Exile_Chopper_Taru_Covered_Black",
	"Exile_Chopper_Taru_Transport_Black",
	"Exile_Chopper_Orca_BlackCustom",
	"Exile_Chopper_Mohawk_FIA",
	"Exile_Chopper_Huron_Black",
	"Exile_Chopper_Hellcat_Green",
	"CUP_B_CH53E_USMC",
	"CUP_B_UH1Y_UNA_F",
	"CUP_B_UH1Y_MEV_F",
	"CUP_C_Mi17_Civilian_RU",
	"CUP_B_Mi17_CDF",
	"CUP_O_Mi17_TK",
	"CUP_B_Mi17_medevac_CDF",
	"CUP_B_Mi171Sh_Unarmed_ACR",
	"CUP_O_Mi8_medevac_CHDKZ",
	"CUP_O_Mi8_medevac_RU",
	"CUP_B_Merlin_HC3_GB",
	"CUP_B_Merlin_HC3A_GB",
	"CUP_B_MH60S_USMC",
	"CUP_B_MH60S_FFV_USMC",
	"CUP_B_AW159_Unarmed_BAF",
	"CUP_B_CH47F_USA",
	"CUP_B_CH47F_GB",
	"CUP_B_UH60M_US",
	"CUP_B_UH60L_US",
	"CUP_B_UH60M_FFV_US",
	"CUP_B_UH60L_FFV_US",
	"CUP_B_UH60M_Unarmed_US",
	"CUP_B_UH60L_Unarmed_US",
	"CUP_B_UH60M_Unarmed_FFV_US",
	"CUP_B_UH60L_Unarmed_FFV_US",
	"CUP_B_UH60M_Unarmed_FFV_MEV_US",
	"CUP_B_UH60L_Unarmed_FFV_MEV_US",
	"CUP_I_UH60L_RACS",
	"CUP_I_UH60L_FFV_RACS",
	"CUP_I_UH60L_Unarmed_RACS",
	"CUP_I_UH60L_Unarmed_FFV_Racs",
	"CUP_I_UH60L_Unarmed_FFV_MEV_Racs",
	"CUP_B_AH1Z_NoWeapons",
	"B_Heli_Transport_01_F",
	"CUP_O_UH1H_TKA",
	"CUP_I_UH1H_TK_GUE",
	"CUP_O_Mi8_CHDKZ",
	"B_Heli_Light_01_armed_F",
	"CUP_B_Mi24_D_MEV_CDF",
	"CUP_O_Mi8_SLA_1",
	"CUP_B_C130J_USMC",
	"CUP_C_DC3_CIV",
	"CUP_C_C47_CIV",
	"I_MRAP_03_hmg_F",
	"B_MRAP_01_hmg_F" */
];

/**
 * List of class names of objects which can be lifted.
 * Liste des noms de classes des objets héliportables.
 */
R3F_LOG_CFG_can_be_lifted = R3F_LOG_CFG_can_be_lifted +
[
	// e.g. : "MyLiftableObjectClassName1", "MyLiftableObjectClassName2"
	// Here comes the Classname for the Vehicle which can be Lifted
/* 	"Exile_Car_Offroad_Repair_Civillian",
	"Exile_Car_Offroad_Repair_Red",
	"Exile_Car_Offroad_Repair_Beige",
	"Exile_Car_Offroad_Repair_White",
	"Exile_Car_Offroad_Repair_Blue",
	"Exile_Car_Offroad_Repair_DarkRed",
	"Exile_Car_Offroad_Repair_BlueCustom",
	"Exile_Car_Offroad_Repair_Guerilla01",
	"Exile_Car_Offroad_Repair_Guerilla02",	
	"Exile_Car_Offroad_Repair_Guerilla03",
	"Exile_Car_Offroad_Repair_Guerilla04",
	"Exile_Car_Offroad_Repair_Guerilla05",
	"Exile_Car_Offroad_Repair_Guerilla06",
	"Exile_Car_Offroad_Repair_Guerilla07",
	"Exile_Car_Offroad_Repair_Guerilla08",
	"Exile_Car_Offroad_Repair_Guerilla09",
	"Exile_Car_Offroad_Repair_Guerilla10",
	"Exile_Car_Offroad_Repair_Guerilla11",
	"Exile_Car_Offroad_Repair_Guerilla12",
	"Exile_Car_Tempest",
	"Exile_Car_Zamak",
	"Exile_Car_HEMMT",
	"Exile_Car_Strider",
	"Exile_Car_Hunter",
	"Exile_Car_Ifrit",
	"Exile_Car_Offroad_Armed_Guerilla01", 
    "Exile_Car_Offroad_Armed_Guerilla02", 
    "Exile_Car_Offroad_Armed_Guerilla03", 
    "Exile_Car_Offroad_Armed_Guerilla04", 
    "Exile_Car_Offroad_Armed_Guerilla05", 
    "Exile_Car_Offroad_Armed_Guerilla06", 
    "Exile_Car_Offroad_Armed_Guerilla07", 
    "Exile_Car_Offroad_Armed_Guerilla08", 
    "Exile_Car_Offroad_Armed_Guerilla09", 
    "Exile_Car_Offroad_Armed_Guerilla10", 
    "Exile_Car_Offroad_Armed_Guerilla11", 
    "Exile_Car_Offroad_Armed_Guerilla12",
    "Exile_Car_SUV_Red", 
    "Exile_Car_SUV_Black", 
    "Exile_Car_SUV_Grey", 
    "Exile_Car_SUV_Orange",
	"Exile_Car_Van_Black", 
    "Exile_Car_Van_White", 
    "Exile_Car_Van_Red", 
    "Exile_Car_Van_Guerilla01", 
    "Exile_Car_Van_Guerilla02", 
    "Exile_Car_Van_Guerilla03", 
    "Exile_Car_Van_Guerilla04", 
    "Exile_Car_Van_Guerilla05", 
    "Exile_Car_Van_Guerilla06", 
    "Exile_Car_Van_Guerilla07", 
    "Exile_Car_Van_Guerilla08",
    "Exile_Car_Offroad_Rusty1", 
    "Exile_Car_Offroad_Rusty2", 
    "Exile_Car_Offroad_Rusty3", 
    "Exile_Car_Offroad_Red", 
    "Exile_Car_Offroad_Beige", 
    "Exile_Car_Offroad_White", 
    "Exile_Car_Offroad_Blue", 
    "Exile_Car_Offroad_DarkRed", 
    "Exile_Car_Offroad_BlueCustom", 
    "Exile_Car_Offroad_Guerilla01", 
    "Exile_Car_Offroad_Guerilla02", 
    "Exile_Car_Offroad_Guerilla03", 
    "Exile_Car_Offroad_Guerilla04", 
    "Exile_Car_Offroad_Guerilla05", 
    "Exile_Car_Offroad_Guerilla06", 
    "Exile_Car_Offroad_Guerilla07", 
    "Exile_Car_Offroad_Guerilla08", 
    "Exile_Car_Offroad_Guerilla09", 
    "Exile_Car_Offroad_Guerilla10", 
    "Exile_Car_Offroad_Guerilla11", 
    "Exile_Car_Offroad_Guerilla12",
	"Exile_Car_Van_Fuel_Black",
	"Exile_Car_Van_Fuel_Red",
	"Exile_Car_Van_Fuel_White",
	"Exile_Car_Van_Fuel_Guerilla01", 
	"Exile_Car_Van_Fuel_Guerilla02", 
	"Exile_Car_Van_Fuel_Guerilla03",
	"Exile_Car_Van_Box_Black",
	"Exile_Car_Van_Box_White",
	"Exile_Car_Van_Box_Red",
	"Exile_Car_Van_Box_Guerilla01", 
	"Exile_Car_Van_Box_Guerilla02", 
	"Exile_Car_Van_Box_Guerilla03", 
	"Exile_Car_Van_Box_Guerilla04", 
	"Exile_Car_Van_Box_Guerilla05", 
	"Exile_Car_Van_Box_Guerilla06", 
	"Exile_Car_Van_Box_Guerilla07", 
	"Exile_Car_Van_Box_Guerilla08",
	"Exile_Car_SUVXL_Black",
	"Exile_Car_Ikarus_Blue",
	"Exile_Car_Ikarus_Red",
	"Exile_Car_Ikarus_Party",
	"Exile_Car_Ural_Open_Worker",
	"Exile_Car_Ural_Open_Blue",
	"Exile_Car_Ural_Open_Yellow",
	"Exile_Car_Ural_Open_Military",
	"Exile_Car_Ural_Covered_Worker",
	"Exile_Car_Ural_Covered_Blue",
	"Exile_Car_Ural_Covered_Yellow",
	"Exile_Car_Ural_Covered_Military",
	"CUP_C_Datsun",
	"CUP_C_Datsun_4seat",
	"CUP_C_Datsun_Plain",
	"CUP_C_Datsun_Covered",
	"CUP_C_Datsun_Tubeframe",
	"CUP_C_Ural_Civ_01",
	"CUP_C_Ural_Civ_02",
	"CUP_C_Ural_Civ_03",
	"CUP_C_Ural_Open_Civ_01",
	"CUP_C_Ural_Open_Civ_02",
	"CUP_C_Ural_Open_Civ_03",
	"CUP_O_Ural_TKA",
	"CUP_O_Ural_RU",
	"CUP_I_Ural_UN",
	"CUP_B_Ural_CDF",
	"CUP_O_Ural_CHDKZ",
	"CUP_O_Ural_SLA",
	"CUP_O_Ural_Open_TKA",
	"CUP_B_Ural_Open_CDF",
	"CUP_O_Ural_Open_RU",
	"CUP_O_Ural_Open_CHDKZ",
	"CUP_O_Ural_Open_SLA",
	"CUP_O_Ural_Empty_SLA",
	"CUP_B_Ural_Empty_CDF",
	"CUP_I_Ural_Empty_UN",
	"CUP_O_Ural_Empty_RU",
	"CUP_O_Ural_Empty_CHDKZ",
	"CUP_O_Ural_Empty_TKA",
	"CUP_O_Ural_Repair_SLA",
	"CUP_O_Ural_Repair_TKA",
	"CUP_O_Ural_Repair_CHDKZ",
	"CUP_O_Ural_Repair_RU",
	"CUP_I_Ural_Repair_UN",
	"CUP_B_Ural_Repair_CDF",
	"CUP_B_Ural_Refuel_CDF",
	"CUP_O_Ural_Refuel_RU",
	"CUP_O_Ural_Refuel_CHDKZ",
	"CUP_O_Ural_Refuel_TKA",
	"CUP_O_Ural_Refuel_SLA",
	"CUP_C_LR_Transport_CTK",
	"CUP_O_LR_Transport_TKA",
	"CUP_O_LR_Transport_TKM",
	"CUP_B_LR_Transport_CZ_W",
	"CUP_B_LR_Transport_CZ_D",
	"CUP_B_LR_Transport_GB_W",
	"CUP_B_LR_Transport_GB_D",
	"CUP_B_LR_Ambulance_CZ_W",
	"CUP_B_LR_Ambulance_CZ_D",
	"CUP_B_LR_Ambulance_GB_W",
	"CUP_B_LR_Ambulance_GB_D",
	"CUP_O_LR_Ambulance_TKA",
	"CUP_C_UAZ_Unarmed_TK_CIV",
	"CUP_O_UAZ_Unarmed_RU",
	"CUP_I_UAZ_Unarmed_UN",
	"CUP_O_UAZ_Unarmed_TKA",
	"CUP_O_UAZ_Unarmed_CHDKZ",
	"CUP_B_UAZ_Unarmed_ACR",
	"CUP_B_UAZ_Unarmed_CDF",
	"CUP_C_UAZ_Open_TK_CIV",
	"CUP_O_UAZ_Open_CHDKZ",
	"CUP_O_UAZ_Open_RU",
	"CUP_O_UAZ_Open_TKA",
	"CUP_I_UAZ_Open_UN",
	"CUP_B_UAZ_Open_ACR",
	"CUP_B_UAZ_Open_CDF",
	"CUP_B_HMMWV_Unarmed_USA",
	"CUP_B_HMMWV_Unarmed_USMC",
	"CUP_B_HMMWV_Ambulance_USMC",
	"CUP_B_HMMWV_Ambulance_USA",
	"CUP_B_HMMWV_Ambulance_ACR",
	"CUP_B_HMMWV_Transport_USA",
	"CUP_C_Golf4_whiteblood_Civ",
	"CUP_C_Golf4_camo_Civ",
	"CUP_C_Golf4_camodigital_Civ",
	"CUP_C_Golf4_camodark_Civ",
	"CUP_C_Golf4_reptile_Civ",
	"CUP_C_Golf4_kitty_Civ",
	"CUP_O_LR_MG_TKM",
	"CUP_O_LR_MG_TKA",
	"CUP_I_Datsun_PK",
	"CUP_I_Datsun_PK_Random",
	"CUP_I_Datsun_PK_TK",
	"CUP_I_Datsun_PK_TK_Random",
	"CUP_O_Datsun_PK",
	"CUP_O_Datsun_PK_Random",
	"CUP_O_UAZ_MG_CHDKZ",
	"CUP_O_UAZ_MG_RU",
	"CUP_O_UAZ_MG_TKA",
	"CUP_I_UAZ_MG_UN",
	"CUP_B_UAZ_MG_ACR",
	"CUP_B_UAZ_MG_CDF",
	"CUP_B_UAZ_AGS30_CDF",
	"CUP_O_UAZ_AGS30_CHDKZ",
	"CUP_O_UAZ_AGS30_RU",
	"CUP_O_UAZ_AGS30_TKA",
	"CUP_I_UAZ_AGS30_UN",
	"CUP_B_BRDM2_HQ_CDF",
	"CUP_O_BRDM2_HQ_SLA",
	"CUP_I_BRDM2_HQ_UN",
	"CUP_I_BRDM2_HQ_NAPA",
	"CUP_I_BRDM2_HQ_TK_Gue",
	"CUP_O_BRDM2_HQ_TKA",
	"CUP_O_BRDM2_HQ_CHDKZ",
	"CUP_O_BRDM2_CHDKZ",
	"CUP_O_BRDM2_SLA",
	"CUP_O_BRDM2_TKA",
	"CUP_I_BRDM2_NAPA",
	"CUP_I_BRDM2_TK_Gue",
	"CUP_I_BRDM2_UN",
	"CUP_B_BRDM2_CDF",
	"CUP_O_BTR60_TK",
	"CUP_O_BTR90_HQ_RU",
	"CUP_BAF_Jackal2_L2A1_W",
	"CUP_BAF_Jackal2_L2A1_D",
	"CUP_BAF_Jackal2_GMG_D",
	"CUP_BAF_Jackal2_GMG_W",
	"CUP_B_LR_Special_CZ_W",
	"CUP_B_LR_Special_Des_CZ_D",
	"CUP_B_LR_MG_CZ_W",
	"CUP_B_LR_MG_GB_W",
	"CUP_B_HMMWV_M1114_USMC",
	"CUP_B_HMMWV_M2_USMC",
	"CUP_B_HMMWV_Crows_M2_USA",
	"CUP_B_HMMWV_M2_GPK_USA",
	"CUP_B_HMMWV_M2_USA",
	"CUP_B_HMMWV_DSHKM_GPK_ACR",
	"CUP_B_HMMWV_AGS_GPK_ACR",
	"CUP_B_HMMWV_MK19_USMC",
	"CUP_B_HMMWV_MK19_USA",
	"CUP_B_HMMWV_Crows_MK19_USA",
	"CUP_B_HMMWV_SOV_USA",
	"I_MRAP_03_hmg_F",
	"B_MRAP_01_hmg_F" */
];


/****** LOAD IN VEHICLE / CHARGER DANS LE VEHICULE ******/

/*
* (EN)
 * This section uses a numeric quantification of capacity and cost of the objets.
 * For example, in a vehicle has a capacity of 100, we will be able to load in 5 objects costing 20 capacity units.
 * The capacity doesn't represent a real volume or weight, but a choice made for gameplay.
 * 
 * (FR)
 * Cette section utilise une quantification numérique de la capacité et du coût des objets.
 * Par exemple, dans un véhicule d'une capacité de 100, nous pouvons charger 5 objets coûtant 20 unités de capacité.
 * La capacité ne représente ni un poids, ni un volume, mais un choix fait pour la jouabilité.
 */

/**
 * List of class names of vehicles or cargo objects which can transport objects.
 * The second element of the nested arrays is the load capacity (in relation with the capacity cost of the objects).
 * 
 * Liste des noms de classes des véhicules ou "objets contenant" pouvant transporter des objets.
 * Le deuxième élément des sous-tableaux est la capacité de chargement (en relation avec le coût de capacité des objets).
 */
R3F_LOG_CFG_can_transport_cargo = R3F_LOG_CFG_can_transport_cargo +
[
	// e.g. : ["MyTransporterClassName1", itsCapacity], ["MyTransporterClassName2", itsCapacity]
	// Here Comes the Vehicle which can Load Stuff
	
	["CUP_B_MV22_USMC", 2000],
	["Exile_Car_Offroad_Rusty1", 100],
	["Exile_Car_Offroad_Rusty2", 100],
	["Exile_Car_Offroad_Rusty3", 100],
	["Exile_Car_Offroad_Repair_Beige", 60],
	["Exile_Car_Offroad_Repair_Blue", 60],
	["Exile_Car_Offroad_Repair_BlueCustom", 60],
	["Exile_Car_Offroad_Repair_Civillian", 60],
	["Exile_Car_Offroad_Repair_DarkRed", 60],
	["Exile_Car_Offroad_Repair_Guerilla01", 60],
	["Exile_Car_Offroad_Repair_Guerilla02", 60],
	["Exile_Car_Offroad_Repair_Guerilla03", 60],
	["Exile_Car_Offroad_Repair_Guerilla04", 60],
	["Exile_Car_Offroad_Repair_Guerilla05", 60],
	["Exile_Car_Offroad_Repair_Guerilla06", 60],
	["Exile_Car_Offroad_Repair_Guerilla07", 60],
	["Exile_Car_Offroad_Repair_Guerilla08", 60],
	["Exile_Car_Offroad_Repair_Guerilla09", 60],
	["Exile_Car_Offroad_Repair_Guerilla10", 60],
	["Exile_Car_Offroad_Repair_Guerilla11", 60],
	["Exile_Car_Offroad_Repair_Guerilla12", 60],
	["Exile_Car_Offroad_Repair_Red", 60],
	["Exile_Car_Offroad_Repair_White", 60],
	["Exile_Car_Offroad_Armed_Guerilla01", 60],
    ["Exile_Car_Offroad_Armed_Guerilla02",  60],
    ["Exile_Car_Offroad_Armed_Guerilla03", 60], 
    ["Exile_Car_Offroad_Armed_Guerilla04", 60],
    ["Exile_Car_Offroad_Armed_Guerilla05", 60], 
    ["Exile_Car_Offroad_Armed_Guerilla06", 60], 
    ["Exile_Car_Offroad_Armed_Guerilla07", 60], 
    ["Exile_Car_Offroad_Armed_Guerilla08", 60],
    ["Exile_Car_Offroad_Armed_Guerilla09", 60], 
    ["Exile_Car_Offroad_Armed_Guerilla10", 60], 
    ["Exile_Car_Offroad_Armed_Guerilla11", 60], 
    ["Exile_Car_Offroad_Armed_Guerilla12", 60],
	["Exile_Car_Offroad_Red", 100],
    ["Exile_Car_Offroad_Beige", 100],
    ["Exile_Car_Offroad_White", 100],
    ["Exile_Car_Offroad_Blue", 100],
    ["Exile_Car_Offroad_DarkRed", 100],
    ["Exile_Car_Offroad_BlueCustom", 100], 
    ["Exile_Car_Offroad_Guerilla01", 100], 
    ["Exile_Car_Offroad_Guerilla02", 100], 
    ["Exile_Car_Offroad_Guerilla03", 100], 
    ["Exile_Car_Offroad_Guerilla04", 100], 
    ["Exile_Car_Offroad_Guerilla05", 100], 
    ["Exile_Car_Offroad_Guerilla06", 100], 
    ["Exile_Car_Offroad_Guerilla07", 100], 
    ["Exile_Car_Offroad_Guerilla08", 100], 
    ["Exile_Car_Offroad_Guerilla09", 100], 
    ["Exile_Car_Offroad_Guerilla10", 100], 
    ["Exile_Car_Offroad_Guerilla11", 100], 
    ["Exile_Car_Offroad_Guerilla12", 100],
	["Exile_Car_Lada_Green", 60],
	["Exile_Car_Lada_Taxi", 60],
	["Exile_Car_Lada_Red", 60],
	["Exile_Car_Lada_White", 60],
	["Exile_Car_Lada_Hipster", 60],
	["Exile_Car_SUV_Red", 60],
	["Exile_Car_SUV_Black", 60],
	["Exile_Car_SUV_Grey", 60],
	["Exile_Car_SUV_Orange", 60],
	["Exile_Car_Van_Black", 240],
    ["Exile_Car_Van_White", 240],
    ["Exile_Car_Van_Red", 240], 
    ["Exile_Car_Van_Guerilla01", 240], 
    ["Exile_Car_Van_Guerilla02", 240], 
    ["Exile_Car_Van_Guerilla03", 240], 
    ["Exile_Car_Van_Guerilla04", 240], 
    ["Exile_Car_Van_Guerilla05", 240], 
    ["Exile_Car_Van_Guerilla06", 240], 
    ["Exile_Car_Van_Guerilla07", 240], 
    ["Exile_Car_Van_Guerilla08", 240],
	["Exile_Car_Van_Box_Black", 240],
    ["Exile_Car_Van_Box_White", 240],
    ["Exile_Car_Van_Box_Red", 240], 
    ["Exile_Car_Van_Box_Guerilla01", 240], 
    ["Exile_Car_Van_Box_Guerilla02", 240], 
    ["Exile_Car_Van_Box_Guerilla03", 240], 
    ["Exile_Car_Van_Box_Guerilla04", 240], 
    ["Exile_Car_Van_Box_Guerilla05", 240], 
    ["Exile_Car_Van_Box_Guerilla06", 240], 
    ["Exile_Car_Van_Box_Guerilla07", 240], 
    ["Exile_Car_Van_Box_Guerilla08", 240],
	["Exile_Bike_QuadBike_Black", 20],
	["Exile_Bike_QuadBike_Blue", 20],
	["Exile_Bike_QuadBike_Red", 20],
	["Exile_Bike_QuadBike_White", 20],
	["Exile_Bike_QuadBike_Nato", 20],
	["Exile_Bike_QuadBike_Csat", 20],
	["Exile_Bike_QuadBike_Fia", 20],
	["Exile_Bike_QuadBike_Guerilla01", 20],
	["Exile_Bike_QuadBike_Guerilla02", 20],
	["Exile_Car_Hatchback_Rusty1", 40],
	["Exile_Car_Hatchback_Rusty2", 40],
	["Exile_Car_Hatchback_Rusty3", 40],
	["Exile_Car_Hatchback_Beige", 40],
	["Exile_Car_Hatchback_BeigeCustom", 40],
	["Exile_Car_Hatchback_Black", 40],
	["Exile_Car_Hatchback_Blue", 40],
	["Exile_Car_Hatchback_Beige", 40],
	["Exile_Car_Hatchback_Beige", 40],
	["Exile_Car_Hatchback_Green", 40], 
	["Exile_Car_Hatchback_Yellow", 40], 
	["Exile_Car_Hatchback_Grey", 40], 
	["Exile_Car_Hatchback_Dark", 40], 
	["Exile_Car_Hatchback_Sport_Red", 40], 
	["Exile_Car_Hatchback_Sport_Blue", 40], 
	["Exile_Car_Hatchback_Sport_Orange", 40], 
	["Exile_Car_Hatchback_Sport_White", 40], 
	["Exile_Car_Hatchback_Sport_Beige", 40], 
	["Exile_Car_Hatchback_Sport_Green", 40],
	["Exile_Bike_QuadBike_Black", 40], 
	["Exile_Bike_QuadBike_Blue", 40], 
	["Exile_Bike_QuadBike_Red", 40], 
	["Exile_Bike_QuadBike_White", 40], 
	["Exile_Bike_QuadBike_Nato", 40], 
	["Exile_Bike_QuadBike_Csat", 40],
	["Exile_Bike_QuadBike_Fia", 40], 
	["Exile_Bike_QuadBike_Guerilla01", 40], 
	["Exile_Bike_QuadBike_Guerilla02", 40], 
	["Exile_Car_Tempest", 600],
	["Exile_Car_Zamak", 400],
	["Exile_Car_HEMMT", 800],
	["Exile_Car_Strider", 180],
	["Exile_Car_Hunter", 140],
	["Exile_Car_Ifrit", 140],
	["Exile_Car_Lada_Green", 40],
	["Exile_Car_Lada_Taxi", 40],
	["Exile_Car_Lada_Red", 40],
	["Exile_Car_Lada_White", 40],
	["Exile_Car_Lada_Hipster", 100],
	["Exile_Car_Volha_White", 40],
	["Exile_Car_Volha_Blue", 40],
	["Exile_Car_Volha_Black", 40],
	["Exile_Car_SUVXL_Black", 100],
	["Exile_Car_Ikarus_Blue", 2000],
	["Exile_Car_Ikarus_Red", 2000],
	["Exile_Car_Ikarus_Party", 2000],
	["Exile_Car_Ural_Open_Worker", 800],
	["Exile_Car_Ural_Open_Blue", 800],
	["Exile_Car_Ural_Open_Yellow", 800],
	["Exile_Car_Ural_Open_Military", 800],
	["Exile_Car_Ural_Covered_Worker", 800],
	["Exile_Car_Ural_Covered_Blue", 800],
	["Exile_Car_Ural_Covered_Yellow", 800],
	["Exile_Car_Ural_Covered_Military", 800],
	["Exile_Chopper_Hummingbird_Green", 100],
	["Exile_Chopper_Hummingbird_Civillian_Wasp", 100],
	["Exile_Chopper_Taru_Black", 100],
	["Exile_Chopper_Taru_Covered_Black", 100],
	["Exile_Chopper_Taru_Transport_Black", 100],
	["Exile_Chopper_Orca_BlackCustom", 100],
	["Exile_Chopper_Mohawk_FIA", 100],
	["Exile_Chopper_Huron_Black", 100],
	["Exile_Chopper_Hellcat_Green", 100],
	["CUP_C_Datsun", 100],
	["CUP_C_Datsun_4seat", 100],
	["CUP_C_Datsun_Plain", 100],
	["CUP_C_Datsun_Covered", 100],
	["CUP_C_Datsun_Tubeframe", 100],
	["CUP_C_Ural_Civ_01", 200],
	["CUP_C_Ural_Civ_02", 200],
	["CUP_C_Ural_Civ_03", 200],
	["CUP_C_Ural_Open_Civ_01", 200],
	["CUP_C_Ural_Open_Civ_02", 200],
	["CUP_C_Ural_Open_Civ_03", 200],
	["CUP_O_Ural_TKA", 200],
	["CUP_O_Ural_RU", 200],
	["CUP_I_Ural_UN", 200],
	["CUP_B_Ural_CDF", 200],
	["CUP_O_Ural_CHDKZ", 200],
	["CUP_O_Ural_SLA", 200],
	["CUP_O_Ural_Open_TKA", 200],
	["CUP_B_Ural_Open_CDF", 200],
	["CUP_O_Ural_Open_RU", 200],
	["CUP_O_Ural_Open_CHDKZ", 200],
	["CUP_O_Ural_Open_SLA", 200],
	["CUP_O_Ural_Empty_SLA", 200],
	["CUP_B_Ural_Empty_CDF", 200],
	["CUP_I_Ural_Empty_UN", 200],
	["CUP_O_Ural_Empty_RU", 200],
	["CUP_O_Ural_Empty_CHDKZ", 200],
	["CUP_O_Ural_Empty_TKA", 200],
	["CUP_O_Ural_Repair_SLA", 200],
	["CUP_O_Ural_Repair_TKA", 200],
	["CUP_O_Ural_Repair_CHDKZ", 200],
	["CUP_O_Ural_Repair_RU", 200],
	["CUP_I_Ural_Repair_UN", 200],
	["CUP_B_Ural_Repair_CDF", 200],
	["CUP_B_Ural_Refuel_CDF", 200],
	["CUP_O_Ural_Refuel_RU", 200],
	["CUP_O_Ural_Refuel_CHDKZ", 200],
	["CUP_O_Ural_Refuel_TKA", 200],
	["CUP_O_Ural_Refuel_SLA", 200],
	["CUP_C_LR_Transport_CTK", 200],
	["CUP_O_LR_Transport_TKA", 200],
	["CUP_O_LR_Transport_TKM", 200],
	["CUP_B_LR_Transport_CZ_W", 200],
	["CUP_B_LR_Transport_CZ_D", 200],
	["CUP_B_LR_Transport_GB_W", 200],
	["CUP_B_LR_Transport_GB_D", 200],
	["CUP_B_LR_Ambulance_CZ_W", 200],
	["CUP_B_LR_Ambulance_CZ_D", 200],
	["CUP_B_LR_Ambulance_GB_W", 200],
	["CUP_B_LR_Ambulance_GB_D", 200],
	["CUP_O_LR_Ambulance_TKA", 200],
	["CUP_C_UAZ_Unarmed_TK_CIV", 100],
	["CUP_O_UAZ_Unarmed_RU", 100],
	["CUP_I_UAZ_Unarmed_UN", 100],
	["CUP_O_UAZ_Unarmed_TKA", 100],
	["CUP_O_UAZ_Unarmed_CHDKZ", 100],
	["CUP_B_UAZ_Unarmed_ACR", 100],
	["CUP_B_UAZ_Unarmed_CDF", 100],
	["CUP_C_UAZ_Open_TK_CIV", 100],
	["CUP_O_UAZ_Open_CHDKZ", 100],
	["CUP_O_UAZ_Open_RU", 100],
	["CUP_O_UAZ_Open_TKA", 100],
	["CUP_I_UAZ_Open_UN", 100],
	["CUP_B_UAZ_Open_ACR", 100],
	["CUP_B_UAZ_Open_CDF", 100],
	["CUP_B_HMMWV_Unarmed_USA", 200],
	["CUP_B_HMMWV_Unarmed_USMC", 200],
	["CUP_B_HMMWV_Ambulance_USMC", 200],
	["CUP_B_HMMWV_Ambulance_USA", 200],
	["CUP_B_HMMWV_Ambulance_ACR", 200],
	["CUP_B_HMMWV_Transport_USA", 200],
	["CUP_C_Golf4_whiteblood_Civ", 200],
	["CUP_C_Golf4_camo_Civ", 200],
	["CUP_C_Golf4_camodigital_Civ", 200],
	["CUP_C_Golf4_camodark_Civ", 200],
	["CUP_C_Golf4_reptile_Civ", 200],
	["CUP_C_Golf4_kitty_Civ", 200],
	["CUP_O_LR_MG_TKM", 200],
	["CUP_O_LR_MG_TKA", 200],
	["CUP_I_Datsun_PK", 100],
	["CUP_I_Datsun_PK_Random", 100],
	["CUP_I_Datsun_PK_TK", 100],
	["CUP_I_Datsun_PK_TK_Random", 100],
	["CUP_O_Datsun_PK", 100],
	["CUP_O_Datsun_PK_Random", 100],
	["CUP_O_UAZ_MG_CHDKZ", 100],
	["CUP_O_UAZ_MG_RU", 100],
	["CUP_O_UAZ_MG_TKA", 100],
	["CUP_I_UAZ_MG_UN", 100],
	["CUP_B_UAZ_MG_ACR", 100],
	["CUP_B_UAZ_MG_CDF", 100],
	["CUP_B_UAZ_AGS30_CDF", 100],
	["CUP_O_UAZ_AGS30_CHDKZ", 100],
	["CUP_O_UAZ_AGS30_RU", 100],
	["CUP_O_UAZ_AGS30_TKA", 100],
	["CUP_I_UAZ_AGS30_UN", 100],
	["CUP_B_BRDM2_HQ_CDF", 200],
	["CUP_O_BRDM2_HQ_SLA", 200],
	["CUP_I_BRDM2_HQ_UN", 200],
	["CUP_I_BRDM2_HQ_NAPA", 200],
	["CUP_I_BRDM2_HQ_TK_Gue", 200],
	["CUP_O_BRDM2_HQ_TKA", 200],
	["CUP_O_BRDM2_HQ_CHDKZ", 200],
	["CUP_O_BRDM2_CHDKZ", 200],
	["CUP_O_BRDM2_SLA", 200],
	["CUP_O_BRDM2_TKA", 200],
	["CUP_I_BRDM2_NAPA", 200],
	["CUP_I_BRDM2_TK_Gue", 200],
	["CUP_I_BRDM2_UN", 200],
	["CUP_B_BRDM2_CDF", 200],
	["CUP_O_BTR60_TK", 200],
	["CUP_O_BTR90_HQ_RU", 200],
	["CUP_BAF_Jackal2_L2A1_W", 200],
	["CUP_BAF_Jackal2_L2A1_D", 200],
	["CUP_BAF_Jackal2_GMG_D", 200],
	["CUP_BAF_Jackal2_GMG_W", 200],
	["CUP_B_LR_Special_CZ_W", 200],
	["CUP_B_LR_Special_Des_CZ_D", 200],
	["CUP_B_LR_MG_CZ_W", 200],
	["CUP_B_LR_MG_GB_W", 200],
	["CUP_B_HMMWV_M1114_USMC", 200],
	["CUP_B_HMMWV_M2_USMC", 200],
	["CUP_B_HMMWV_Crows_M2_USA", 200],
	["CUP_B_HMMWV_M2_GPK_USA", 200],
	["CUP_B_HMMWV_M2_USA", 200],
	["CUP_B_HMMWV_DSHKM_GPK_ACR", 200],
	["CUP_B_HMMWV_AGS_GPK_ACR", 200],
	["CUP_B_HMMWV_MK19_USMC", 200],
	["CUP_B_HMMWV_MK19_USA", 200],
	["CUP_B_HMMWV_Crows_MK19_USA", 200],
	["CUP_B_HMMWV_SOV_USA", 200],
	["CUP_B_CH53E_USMC", 1000],
	["CUP_B_UH1Y_UNA_F", 350],
	["CUP_B_UH1Y_MEV_F", 350],
	["CUP_C_Mi17_Civilian_RU", 500],
	["CUP_B_Mi17_CDF", 500],
	["CUP_O_Mi17_TK", 500],
	["CUP_B_Mi17_medevac_CDF", 500],
	["CUP_B_Mi171Sh_Unarmed_ACR", 500],
	["CUP_O_Mi8_medevac_CHDKZ", 400],
	["CUP_O_Mi8_medevac_RU", 400],
	["CUP_B_Merlin_HC3_GB", 400],
	["CUP_B_Merlin_HC3A_GB", 400],
	["CUP_B_MH60S_USMC", 400],
	["CUP_B_MH60S_FFV_USMC", 400],
	["CUP_B_AW159_Unarmed_BAF", 400],
	["CUP_B_CH47F_USA", 1000],
	["CUP_B_CH47F_GB", 1000],
	["CUP_B_UH60M_US", 400],
	["CUP_B_UH60L_US", 400],
	["CUP_B_UH60M_FFV_US", 400],
	["CUP_B_UH60L_FFV_US", 400],
	["CUP_B_UH60M_Unarmed_US", 400],
	["CUP_B_UH60L_Unarmed_US", 400],
	["CUP_B_UH60M_Unarmed_FFV_US", 400],
	["CUP_B_UH60L_Unarmed_FFV_US", 400],
	["CUP_B_UH60M_Unarmed_FFV_MEV_US", 400],
	["CUP_B_UH60L_Unarmed_FFV_MEV_US", 400],
	["CUP_I_UH60L_RACS", 400],
	["CUP_I_UH60L_FFV_RACS", 400],
	["CUP_I_UH60L_Unarmed_RACS", 400],
	["CUP_I_UH60L_Unarmed_FFV_Racs", 400],
	["CUP_I_UH60L_Unarmed_FFV_MEV_Racs", 400],
	["CUP_B_AH1Z_NoWeapons", 400],
	["B_Heli_Transport_01_F", 500],
	["CUP_O_UH1H_TKA", 350],
	["CUP_I_UH1H_TK_GUE", 350],
	["CUP_O_Mi8_CHDKZ", 1000],
	["B_Heli_Light_01_armed_F", 100],
	["CUP_B_Mi24_D_MEV_CDF", 1000],
	["CUP_O_Mi8_SLA_1", 400],
	["CUP_B_C130J_USMC", 1000],
	["CUP_C_DC3_CIV", 1000],
	["CUP_C_C47_CIV", 1000],
	["I_MRAP_03_hmg_F", 200],
	["B_MRAP_01_hmg_F", 200]
];

/**
 * List of class names of objects which can be loaded in transport vehicle/cargo.
 * The second element of the nested arrays is the cost capacity (in relation with the capacity of the vehicles).
 * 
 * Liste des noms de classes des objets transportables.
 * Le deuxième élément des sous-tableaux est le coût de capacité (en relation avec la capacité des véhicules).
 */
R3F_LOG_CFG_can_be_transported_cargo = R3F_LOG_CFG_can_be_transported_cargo +
[
	// e.g. : ["MyTransportableObjectClassName1", itsCost], ["MyTransportableObjectClassName2", itsCost]
	// Here Comes the Stuff what you want to load in the Vehicle  example: ["IG_supplyCrate_F", 40]
	
	["Box_NATO_WPS_F", 20],
	["B_supplyCrate_F", 40],
	["IG_supplyCrate_F", 40],
	["I_CargoNET_01_F", 40],
	["I_CargoNet_01_ammo_F", 40],
	["O_CargoNet_01_ammo_F", 40],
	["B_CargoNet_01_ammo_F", 40],
	["I_supplyCrate_F", 40],
	["Box_East_AmmoVeh_F", 40],
	["Box_NATO_AmmoVeh_F", 40],
	["B_HMG_01_high_F", 20],
	["Exile_Item_Storagecrate", 20],
	["Exile_Car_Offroad_Repair_Civillian", 250],
	["Exile_Car_Offroad_Repair_Red", 250],
	["Exile_Car_Offroad_Repair_Beige", 250],
	["Exile_Car_Offroad_Repair_White", 250],
	["Exile_Car_Offroad_Repair_Blue", 250],
	["Exile_Car_Offroad_Repair_DarkRed", 250],
	["Exile_Car_Offroad_Repair_BlueCustom", 250],
	["Exile_Car_Offroad_Repair_Guerilla01", 250],
	["Exile_Car_Offroad_Repair_Guerilla02", 250],	
	["Exile_Car_Offroad_Repair_Guerilla03", 250],
	["Exile_Car_Offroad_Repair_Guerilla04", 250],
	["Exile_Car_Offroad_Repair_Guerilla05", 250],
	["Exile_Car_Offroad_Repair_Guerilla06", 250],
	["Exile_Car_Offroad_Repair_Guerilla07", 250],
	["Exile_Car_Offroad_Repair_Guerilla08", 250],
	["Exile_Car_Offroad_Repair_Guerilla09", 250],
	["Exile_Car_Offroad_Repair_Guerilla10", 250],
	["Exile_Car_Offroad_Repair_Guerilla11", 250],
	["Exile_Car_Offroad_Repair_Guerilla12", 250],
	["Exile_Car_Tempest", 250],
	["Exile_Car_Zamak", 250],
	["Exile_Car_HEMMT", 250],
	["Exile_Car_Strider", 250],
	["Exile_Car_Hunter", 250],
	["Exile_Car_Ifrit", 250],
	["Exile_Car_Offroad_Armed_Guerilla01", 250], 
	["Exile_Car_Offroad_Armed_Guerilla02", 250], 
	["Exile_Car_Offroad_Armed_Guerilla03", 250], 
	["Exile_Car_Offroad_Armed_Guerilla04", 250], 
	["Exile_Car_Offroad_Armed_Guerilla05", 250], 
	["Exile_Car_Offroad_Armed_Guerilla06", 250], 
	["Exile_Car_Offroad_Armed_Guerilla07", 250], 
	["Exile_Car_Offroad_Armed_Guerilla08", 250], 
	["Exile_Car_Offroad_Armed_Guerilla09", 250], 
	["Exile_Car_Offroad_Armed_Guerilla10", 250], 
	["Exile_Car_Offroad_Armed_Guerilla11", 250], 
	["Exile_Car_Offroad_Armed_Guerilla12", 250],
	["Exile_Car_SUV_Red", 250], 
	["Exile_Car_SUV_Black", 250], 
	["Exile_Car_SUV_Grey", 250], 
	["Exile_Car_SUV_Orange", 250],
	["Exile_Car_Van_Black", 250], 
	["Exile_Car_Van_White", 250], 
	["Exile_Car_Van_Red", 250], 
	["Exile_Car_Van_Guerilla01", 250], 
	["Exile_Car_Van_Guerilla02", 250], 
	["Exile_Car_Van_Guerilla03", 250], 
	["Exile_Car_Van_Guerilla04", 250], 
	["Exile_Car_Van_Guerilla05", 250], 
	["Exile_Car_Van_Guerilla06", 250], 
	["Exile_Car_Van_Guerilla07", 250], 
	["Exile_Car_Van_Guerilla08", 250],
	["Exile_Car_Offroad_Rusty1", 250], 
	["Exile_Car_Offroad_Rusty2", 250], 
	["Exile_Car_Offroad_Rusty3", 250], 
	["Exile_Car_Offroad_Red", 250], 
	["Exile_Car_Offroad_Beige", 250], 
	["Exile_Car_Offroad_White", 250], 
	["Exile_Car_Offroad_Blue", 250], 
	["Exile_Car_Offroad_DarkRed", 250], 
	["Exile_Car_Offroad_BlueCustom", 250], 
	["Exile_Car_Offroad_Guerilla01", 250], 
	["Exile_Car_Offroad_Guerilla02", 250], 
	["Exile_Car_Offroad_Guerilla03", 250], 
	["Exile_Car_Offroad_Guerilla04", 250], 
	["Exile_Car_Offroad_Guerilla05", 250], 
	["Exile_Car_Offroad_Guerilla06", 250], 
	["Exile_Car_Offroad_Guerilla07", 250], 
	["Exile_Car_Offroad_Guerilla08", 250], 
	["Exile_Car_Offroad_Guerilla09", 250], 
	["Exile_Car_Offroad_Guerilla10", 250], 
	["Exile_Car_Offroad_Guerilla11", 250], 
	["Exile_Car_Offroad_Guerilla12", 250],
	["Exile_Car_Van_Fuel_Black", 250],
	["Exile_Car_Van_Fuel_Red", 250],
	["Exile_Car_Van_Fuel_White", 250],
	["Exile_Car_Van_Fuel_Guerilla01", 250], 
	["Exile_Car_Van_Fuel_Guerilla02", 250], 
	["Exile_Car_Van_Fuel_Guerilla03", 250],
	["Exile_Car_Van_Box_Black", 250],
	["Exile_Car_Van_Box_White", 250],
	["Exile_Car_Van_Box_Red", 250],
	["Exile_Car_Van_Box_Guerilla01", 250], 
	["Exile_Car_Van_Box_Guerilla02", 250], 
	["Exile_Car_Van_Box_Guerilla03", 250], 
	["Exile_Car_Van_Box_Guerilla04", 250], 
	["Exile_Car_Van_Box_Guerilla05", 250], 
	["Exile_Car_Van_Box_Guerilla06", 250], 
	["Exile_Car_Van_Box_Guerilla07", 250], 
	["Exile_Car_Van_Box_Guerilla08", 250],
	["Exile_Car_SUVXL_Black", 250],
	["Exile_Car_Ikarus_Blue", 250],
	["Exile_Car_Ikarus_Red", 250],
	["Exile_Car_Ikarus_Party", 250],
	["Exile_Car_Ural_Open_Worker", 250],
	["Exile_Car_Ural_Open_Blue", 250],
	["Exile_Car_Ural_Open_Yellow", 250],
	["Exile_Car_Ural_Open_Military", 250],
	["Exile_Car_Ural_Covered_Worker", 250],
	["Exile_Car_Ural_Covered_Blue", 250],
	["Exile_Car_Ural_Covered_Yellow", 250],
	["Exile_Car_Ural_Covered_Military", 250],
	["CUP_C_Datsun", 250],
	["CUP_C_Datsun_4seat", 250],
	["CUP_C_Datsun_Plain", 250],
	["CUP_C_Datsun_Covered", 250],
	["CUP_C_Datsun_Tubeframe", 250],
	["CUP_C_Ural_Civ_01", 250],
	["CUP_C_Ural_Civ_02", 250],
	["CUP_C_Ural_Civ_03", 250],
	["CUP_C_Ural_Open_Civ_01", 250],
	["CUP_C_Ural_Open_Civ_02", 250],
	["CUP_C_Ural_Open_Civ_03", 250],
	["CUP_O_Ural_TKA", 250],
	["CUP_O_Ural_RU", 250],
	["CUP_I_Ural_UN", 250],
	["CUP_B_Ural_CDF", 250],
	["CUP_O_Ural_CHDKZ", 250],
	["CUP_O_Ural_SLA", 250],
	["CUP_O_Ural_Open_TKA", 250],
	["CUP_B_Ural_Open_CDF", 250],
	["CUP_O_Ural_Open_RU", 250],
	["CUP_O_Ural_Open_CHDKZ", 250],
	["CUP_O_Ural_Open_SLA", 250],
	["CUP_O_Ural_Empty_SLA", 250],
	["CUP_B_Ural_Empty_CDF", 250],
	["CUP_I_Ural_Empty_UN", 250],
	["CUP_O_Ural_Empty_RU", 250],
	["CUP_O_Ural_Empty_CHDKZ", 250],
	["CUP_O_Ural_Empty_TKA", 250],
	["CUP_O_Ural_Repair_SLA", 250],
	["CUP_O_Ural_Repair_TKA", 250],
	["CUP_O_Ural_Repair_CHDKZ", 250],
	["CUP_O_Ural_Repair_RU", 250],
	["CUP_I_Ural_Repair_UN", 250],
	["CUP_B_Ural_Repair_CDF", 250],
	["CUP_B_Ural_Refuel_CDF", 250],
	["CUP_O_Ural_Refuel_RU", 250],
	["CUP_O_Ural_Refuel_CHDKZ", 250],
	["CUP_O_Ural_Refuel_TKA", 250],
	["CUP_O_Ural_Refuel_SLA", 250],
	["CUP_C_LR_Transport_CTK", 250],
	["CUP_O_LR_Transport_TKA", 250],
	["CUP_O_LR_Transport_TKM", 250],
	["CUP_B_LR_Transport_CZ_W", 250],
	["CUP_B_LR_Transport_CZ_D", 250],
	["CUP_B_LR_Transport_GB_W", 250],
	["CUP_B_LR_Transport_GB_D", 250],
	["CUP_B_LR_Ambulance_CZ_W", 250],
	["CUP_B_LR_Ambulance_CZ_D", 250],
	["CUP_B_LR_Ambulance_GB_W", 250],
	["CUP_B_LR_Ambulance_GB_D", 250],
	["CUP_O_LR_Ambulance_TKA", 250],
	["CUP_C_UAZ_Unarmed_TK_CIV", 250],
	["CUP_O_UAZ_Unarmed_RU", 250],
	["CUP_I_UAZ_Unarmed_UN", 250],
	["CUP_O_UAZ_Unarmed_TKA", 250],
	["CUP_O_UAZ_Unarmed_CHDKZ", 250],
	["CUP_B_UAZ_Unarmed_ACR", 250],
	["CUP_B_UAZ_Unarmed_CDF", 250],
	["CUP_C_UAZ_Open_TK_CIV", 250],
	["CUP_O_UAZ_Open_CHDKZ", 250],
	["CUP_O_UAZ_Open_RU", 250],
	["CUP_O_UAZ_Open_TKA", 250],
	["CUP_I_UAZ_Open_UN", 250],
	["CUP_B_UAZ_Open_ACR", 250],
	["CUP_B_UAZ_Open_CDF", 250],
	["CUP_B_HMMWV_Unarmed_USA", 250],
	["CUP_B_HMMWV_Unarmed_USMC", 250],
	["CUP_B_HMMWV_Ambulance_USMC", 250],
	["CUP_B_HMMWV_Ambulance_USA", 250],
	["CUP_B_HMMWV_Ambulance_ACR", 250],
	["CUP_B_HMMWV_Transport_USA", 250],
	["CUP_C_Golf4_whiteblood_Civ", 250],
	["CUP_C_Golf4_camo_Civ", 250],
	["CUP_C_Golf4_camodigital_Civ", 250],
	["CUP_C_Golf4_camodark_Civ", 250],
	["CUP_C_Golf4_reptile_Civ", 250],
	["CUP_C_Golf4_kitty_Civ", 250],
	["CUP_O_LR_MG_TKM", 250],
	["CUP_O_LR_MG_TKA", 250],
	["CUP_I_Datsun_PK", 250],
	["CUP_I_Datsun_PK_Random", 250],
	["CUP_I_Datsun_PK_TK", 250],
	["CUP_I_Datsun_PK_TK_Random", 250],
	["CUP_O_Datsun_PK", 250],
	["CUP_O_Datsun_PK_Random", 250],
	["CUP_O_UAZ_MG_CHDKZ", 250],
	["CUP_O_UAZ_MG_RU", 250],
	["CUP_O_UAZ_MG_TKA", 250],
	["CUP_I_UAZ_MG_UN", 250],
	["CUP_B_UAZ_MG_ACR", 250],
	["CUP_B_UAZ_MG_CDF", 250],
	["CUP_B_UAZ_AGS30_CDF", 250],
	["CUP_O_UAZ_AGS30_CHDKZ", 250],
	["CUP_O_UAZ_AGS30_RU", 250],
	["CUP_O_UAZ_AGS30_TKA", 250],
	["CUP_I_UAZ_AGS30_UN", 250],
	["CUP_B_BRDM2_HQ_CDF", 250],
	["CUP_O_BRDM2_HQ_SLA", 250],
	["CUP_I_BRDM2_HQ_UN", 250],
	["CUP_I_BRDM2_HQ_NAPA", 250],
	["CUP_I_BRDM2_HQ_TK_Gue", 250],
	["CUP_O_BRDM2_HQ_TKA", 250],
	["CUP_O_BRDM2_HQ_CHDKZ", 250],
	["CUP_O_BRDM2_CHDKZ", 250],
	["CUP_O_BRDM2_SLA", 250],
	["CUP_O_BRDM2_TKA", 250],
	["CUP_I_BRDM2_NAPA", 250],
	["CUP_I_BRDM2_TK_Gue", 250],
	["CUP_I_BRDM2_UN", 250],
	["CUP_B_BRDM2_CDF", 250],
	["CUP_O_BTR60_TK", 250],
	["CUP_O_BTR90_HQ_RU", 250],
	["CUP_BAF_Jackal2_L2A1_W", 250],
	["CUP_BAF_Jackal2_L2A1_D", 250],
	["CUP_BAF_Jackal2_GMG_D", 250],
	["CUP_BAF_Jackal2_GMG_W", 250],
	["CUP_B_LR_Special_CZ_W", 250],
	["CUP_B_LR_Special_Des_CZ_D", 250],
	["CUP_B_LR_MG_CZ_W", 250],
	["CUP_B_LR_MG_GB_W", 250],
	["CUP_B_HMMWV_M1114_USMC", 250],
	["CUP_B_HMMWV_M2_USMC", 250],
	["CUP_B_HMMWV_Crows_M2_USA", 250],
	["CUP_B_HMMWV_M2_GPK_USA", 250],
	["CUP_B_HMMWV_M2_USA", 250],
	["CUP_B_HMMWV_DSHKM_GPK_ACR", 250],
	["CUP_B_HMMWV_AGS_GPK_ACR", 250],
	["CUP_B_HMMWV_MK19_USMC", 250],
	["CUP_B_HMMWV_MK19_USA", 250],
	["CUP_B_HMMWV_Crows_MK19_USA", 250],
	["CUP_B_HMMWV_SOV_USA", 250],
	["I_MRAP_03_hmg_F", 250],
	["B_MRAP_01_hmg_F", 250]
	
];

/****** MOVABLE-BY-PLAYER OBJECTS / OBJETS DEPLACABLES PAR LE JOUEUR ******/

/**
 * List of class names of objects which can be carried and moved by a player.
 * Liste des noms de classes des objets qui peuvent être portés et déplacés par le joueur.
 */
R3F_LOG_CFG_can_be_moved_by_player = R3F_LOG_CFG_can_be_moved_by_player +
[
	// Here Comes that stuff in what a player can Move 
	// e.g. : "MyMovableObjectClassName1", "MyMovableObjectClassName2"
	"CargoNet_01_box_F",
	"Box_NATO_AmmoVeh_F",
	"B_supplyCrate_F",
	"I_CargoNET_01_F",
	"Box_NATO_Wps_F",
	"C_supplyCrate_F",
	"IG_supplyCrate_F",
	"Box_IND_AmmoVeh_F",
	"B_Slingload_01_Cargo_F",
	"B_Slingload_01_Fuel_F",
	"B_Slingload_01_Ammo_F",
	"B_Slingload_01_Medevac_F",
	"B_Slingload_01_Repair_F",
	"Land_Pod_Heli_Transport_04_covered_F",
	"Land_Pod_Heli_Transport_04_fuel_F",
	"Land_Pod_Heli_Transport_04_box_F",
	"Land_Pod_Heli_Transport_04_repair_F",
	"Land_Pod_Heli_Transport_04_medevac_F",
	"Land_Pod_Heli_Transport_04_bench_F",
	"Land_Pod_Heli_Transport_04_covered_black_F",
	"Land_Pod_Heli_Transport_04_fuel_black_F",
	"Land_Pod_Heli_Transport_04_box_black_F",
	"Land_Pod_Heli_Transport_04_repair_black_F",
	"Land_Pod_Heli_Transport_04_medevac_black_F",
	"Land_Pod_Heli_Transport_04_bench_black_F",
	"B_HMG_01_high_F",
	"I_CargoNet_01_ammo_F",
	"O_CargoNet_01_ammo_F",
	"B_CargoNet_01_ammo_F",
	"I_supplyCrate_F",
	"Box_East_AmmoVeh_F",
	"Exile_Item_Storagecrate"

	
];
